name: Control Heroku Dyno

on:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  control:
    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Export API Key
        run: echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> $GITHUB_ENV

      - name: Stop Dyno
        if: github.event.schedule == '0 14 * * *'
        run: heroku ps:scale web=0 -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Start Dyno
        if: github.event.schedule == '0 0 * * *'
        run: heroku ps:scale web=1 -a ${{ secrets.HEROKU_APP_NAME }}