name: Stop Heroku TEST

on:
  schedule:
    - cron: '* * * * *'  # 9:05 JST

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> $GITHUB_ENV
      - run: heroku ps:scale web=0 -a ${{ secrets.HEROKU_APP_NAME }}